### ISSUE TITLE
Support for Corner Radius

### ISSUE THREAD

**Issue by mingsai** [madprops/Msg#7]
Any chance that you could add support for rounding the corners of the various message viewers? Probably just exposing the appropriate property using something similar to:

<div id="target">Lorem Ipsum</div>

<script type="text/javascript">
    var target = document.getElementById("target");
    target.style.borderTopLeftRadius = "20px";
</script>

**Comment by madprops** [comment]
Just tried it. The problem is that the X in the corner to close the modals get out of place, they look weird, and making it behave differently makes it more complex. Fortunately, this is very easy to do with css, take a look in the documentation about the class names and how to style them, for instance, the window element of a modal with id "mymodal" can be styled with #Msg-window-mymodal , or if you want to affect all modals just style the .Msg-window class.

Hope this helps.
